Implement traffic control for IPv6
openshift-kni/eapol-operator pull request #8
Opened 2023-05-09 13:00 UTC by pperiyasamy

This provides a facility to allow ipv6 traffic on specified ports irrespective of client being authenticated or not. The specified port is applied for both tcp and udp protocols.

2023-05-23 17:19 UTC, lack requested changes

2023-05-23 17:19 UTC, lack commented on api/v1/authenticator_types.go
> +	IPv6 []int `json:"ipv6,omitempty"`
Why would we want a different list of ports here?  If we need to combine TCP and UDP for IPv6, why not just combine the `Tcp` and `Udp` lists we already have?

2023-05-24 09:01 UTC, pperiyasamy commented on api/v1/authenticator_types.go
> +	IPv6 []int `json:"ipv6,omitempty"`
oh! yes, done.

2023-05-25 13:56 UTC, lack approved these changes

2023-05-25 13:56 UTC, merged